map:
  style: mapbox://styles/mapbox/light-v9
  center: [42.556564, 1.533476] # Casa de la Muntanya
  zoom: 17
  maxZoom: 18
  minZoom: 11
  maxBounds: [[42.254118, 1.261305], [42.754004, 1.902439]]

  controls:
    zoom:
      position: topright
    scale:
      position: bottomleft
      imperial: false
    compare:
      thumbPosition: 100%
      orientation: vertical
      url: https://api.mapbox.com/styles/v1/mapbox/satellite-v9/tiles/256/{z}/{x}/{y}?access_token={accessToken}
      options:
        attribution: &copy; Mapbox
        token: VITE_MAPBOX_TOKEN

  tiles:
    - name: monochrome
      url: https://api.mapbox.com/styles/v1/markusand/ck4g89u466i301cqgk2cv5fnh/tiles/256/{z}/{x}/{y}@2x?access_token={accessToken}
      options:
        attribution: &copy; mapbox
        token: VITE_MAPBOX_TOKEN

filters:
  profiles:
    - CASUAL
    - TREKKER
    - FAMILY
    - IGER
    - RUNNER
    - SKIER
    - CLIMBER
    - BIKER
    - FISHER
  distance:
    min: 1000
    max: 30000
    step: 1000
    unit:
      type: length
      from: m
      to: km
  duration:
    min: 3600
    max: 36000
    step: 3600
    unit:
      type: time
      from: s
      to: h
  drop_positive:
    min: 0
    max: 2000
    step: 100
    unit:
      type: length
      from: m
      to: m
  origin:
    - Canillo
    - Encamp
    - Ordino
    - La Massana
    - Andorra la Vella
    - Sant Julià de Lòria
    - Escaldes Engordany
  wildlife:
    - RUPICABRA
    - MARMOTA
    - SALMO_TRUTTA
    - TRITURUS
    - TETRAO
    - LAGOPUS
  culture:
    - ROMANESQUE
    - DRY_STONE
    - ART
