principles:
  - plan
  - equip
  - adapt
  - notify

equipment:
  essential:
    - clothes
    - shoes
    - water
    - food
    - raincoat
    - first_aid_kit
    - mobile_phone
    - map_compass
    - sun_protection
    - thermal_blanket
  recommended:
    - gps
    - knife
    - lighter
    - flashlight
    - sandals
